[fs_storage]

[fs_storage.LS3]
__autocreate = {"name": "Local S3 Storage"}
code=LS3
protocol=s3
directory_path=courtneycookies
options={"endpoint_url": "http://s3:9000", "key": "myaccesskey", "secret": "mysecretkey"}
force_db_for_db_attachment_rules=true
s3_uses_signed_url_for_x_sendfile=true
autovaccuum_gc=true
use_x_sendfile_to_serve_internal_url=true
